### ISSUE TITLE
安全需要，不允许读取超大变长数组

### ISSUE THREAD

**Issue by nnhy** [NewLifeX/X#104]
NewLife.XException: 安全需要，不允许读取超大变长数组 2,841>2,048
   at NewLife.Serialization.BinaryGeneral.ReadBytes(Int32 count)
   at NewLife.Serialization.BinaryGeneral.ReadString()
   at NewLife.Serialization.BinaryGeneral.TryRead(Type type, Object& value)
   at NewLife.Serialization.Binary.TryRead(Type type, Object& value)
   at NewLife.Serialization.Binary.Read(Type type)
   at NewLife.Data.DbTable.ReadData(Binary bn, Int32 rows)
   at XCode.DataAccessLayer.DbPackage.Restore(Stream stream, IDataTable table)
   at XCode.DataAccessLayer.DbPackage.<>c__DisplayClass25_0.<Restore>b__0(Stream s)
   at System.IO.PathHelper.OpenRead(FileInfo file, Boolean compressed, Action`1 func)
   at XCode.DataAccessLayer.DbPackage.Restore(String file, IDataTable table, Boolean setSchema)
   at XCode.DataAccessLayer.DAL.Restore(String file, IDataTable table, Boolean setSchema)
   at NewLife.Cube.EntityController`1.Restore()

**Comment by nnhy** [comment]
已查明，该错误起因是二进制序列化内部的安全保护屏障设置过低，导致读取超大数据（>2048字节）时报错
