### ISSUE TITLE
apiclient调用时总是异常

### ISSUE THREAD

**Issue by goodtogood** [NewLifeX/X#87]
新手 刚开始学习 **X** 库，很多地方没理清，
照猫画虎弄凑了个demo，但总是异常
请大佬百忙中回答一下，谢谢！！

服务端

using System;

```
using System;
namespace NewLife.RPC
{
    using System;
    using System.Globalization;
    using System.Linq;
    using System.Net;

    using NewLife.Data;
    using NewLife.Log;
    using NewLife.Net;
    using NewLife.Remoting;

    class Program
    {
        static void Main(string[] args)
        {
            var netUri = new NetUri(NetType.Tcp, IPAddress.Any, 5001);
            using var server = new ApiServer(netUri)
                                   {
                                       Log = XTrace.Log,
                                       EncoderLog = XTrace.Log,
                                       ShowError = true
                                   };
            server.Register<BigController>();
            server.Start();
            Console.ReadKey();
        }

        class BigController
        {
            public int Sum(int a, int b)
            {
                return a + b;
            }

            public string ToUpper(string str)
            {
                return str.ToUpper();
            }

            public Packet Test(Packet pk)
            {
                var buf = pk.ReadBytes().Select(e => (Byte)(e ^ 'x')).ToArray();

                return buf;
            }
        }
    }
}

```

客户端

```
using System;

namespace NewLife.RPC.Client
{
    using NewLife.Data;
    using NewLife.Log;
    using NewLife.Remoting;

    class Program
    {
        private static ApiClient client;
        static void Main(string[] args)
        {
            XTrace.UseConsole(true);
            client = new ApiClient("tcp://127.0.0.1:5001")
                         {
                             Log = XTrace.Log, EncoderLog = XTrace.Log, ShowError = true
                         };

            var buf = new byte[2 * 1024];

            //正常
            var test = client.InvokeAsync<Packet>("Big/Test", buf);
            XTrace.WriteLine($"send  {buf.Length}  receive  {test.Result.Count}");



            //异常
            var s = client.Invoke<int>("Big/Sum", new[] { 2, 3 });
            XTrace.WriteLine($"sum sync {s}");

            var sum = client.InvokeAsync<int>("Big/Sum", new[] { 2, 3 }).GetAwaiter();
            XTrace.WriteLine(sum.GetResult().ToString());

            var upper = client.InvokeAsync<string>("Big/ToUpper", "newlife").GetAwaiter();
            XTrace.WriteLine(upper.GetResult());
        }

    }
}

```

异常信息

```
16:55:26.958  1 N - Api 集群：NewLife.Remoting.ClientSingleCluster
16:55:26.971  1 N - Big/Test=>[2048]
16:55:26.975  1 N - 集群转移：tcp://127.0.0.1:5001
16:55:27.072  1 N - NewLife.Core v8.11.2021.0904 Build 2021-09-04 13:36:04 .NETCoreApp,Version=v5.0
16:55:27.073  1 N - X组件核心库 ?2002-2021 NewLife
16:55:27.073  1 N - NewLife.RPC.Client v1.0.0 Build 2000-01-01 .NETCoreApp,Version=v5.0
16:55:27.074  1 N - NewLife.RPC.Client
16:55:27.075  1 N - send  2048  receive  2048
16:55:27.081  5 Y 1 Big/Sum=>[2,3]
16:55:27.101  1 N - System.AggregateException: One or more errors occurred. (Object reference not set to an instance of
an object.)
 ---> NewLife.Remoting.ApiException: Object reference not set to an instance of an object.
   at NewLife.Remoting.ApiClient.InvokeWithClientAsync[TResult](ISocketClient client, String action, Object args, Byte f
lag)
   at NewLife.Remoting.ApiClient.InvokeAsync[TResult](String action, Object args)
   at NewLife.Remoting.ApiClient.InvokeAsync[TResult](String action, Object args)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NewLife.Remoting.ApiClient.Invoke[TResult](String action, Object args)
   at NewLife.RPC.Client.Program.Main(String[] args) in L:\NewLife\NewLife.RPC\NewLife.RPC.Client\Program.c
s:line 29
16:55:27.113  1 N - 异常退出！
```

**Comment by nnhy** [comment]
今晚我跑一下，你也可以到群里提醒我

**Comment by goodtogood** [comment]
经过大佬指点，发现犯了低级错误，参数传的有问题，应该如下

` var rs = client.Invoke<Int32>("Big/Sum", new { a = 123, b = 456 });`

**Comment by nnhy** [comment]
RPC通信ApiServer
https://www.yuque.com/smartstone/nx/api_server
